### ISSUE TITLE
จะไปกินเมื่อไหร่

### ISSUE THREAD

**Issue by TeetuchPalm** [TeetuchPalm/Shindo#2]
อยากกินเเล้ว

**Comment by chavakan209** [comment]
#1

**Comment by chavakan209** [comment]
@TeetuchPalm 💘 🤠 ☮️ 🍇 🐱 🐈 😹 🐈‍⬛ 😸

**Comment by chavakan209** [comment]
https://github.com/TeetuchPalm/Shindo/pull/3#issuecomment-1449604040
